version: "3.8"
x-namada: &namada-common
  restart: unless-stopped
  build:
    dockerfile: docker/Dockerfile
    context: .
    args:
      - NAMADA_TAG=${NAMADA_TAG}
      - BUILD_WASM=true
  image: arashidos/namada:${NAMADA_TAG}
  entrypoint: ["sh", "/docker-entrypoint-scripts.d/start-node.sh"]
  networks:
    namada:
services:
  namada-1:
    <<: *namada-common
    hostname: namada-1
    volumes:
      - ./config/genesis:/genesis:ro
      - ./config/make_balances.py:/scripts/make_balances.py
      - ./config/update_params.py:/scripts/update_params.py
      - ./masp-params:/root/.masp-params
      - ./config/start-node.sh:/docker-entrypoint-scripts.d/start-node.sh
      - namada-shared:/root/.namada-shared
      - namada-1_data:/root/.local/share/namada
    environment:
      - GENESIS_DELAY=${GENESIS_DELAY}
      - EXTIP=${EXTIP}
    ports:
      - "${P2P_PORT}:26656" # p2p
      - "${RPC_PORT}:26657" # http rpc
      - "${SERVE_PORT}:8123" # configs server

  namada-2:
    <<: *namada-common
    hostname: namada-2
    volumes:
      - ./masp-params:/root/.masp-params
      - ./config/start-node.sh:/docker-entrypoint-scripts.d/start-node.sh
      - namada-shared:/root/.namada-shared
      - namada-2_data:/root/.local/share/namada
    ports:
      - "26656" # p2p
      - "26657" # http rpc

  namada-3:
    <<: *namada-common
    hostname: namada-3
    volumes:
      - ./masp-params:/root/.masp-params
      - ./config/start-node.sh:/docker-entrypoint-scripts.d/start-node.sh
      - namada-shared:/root/.namada-shared
      - namada-3_data:/root/.local/share/namada
    ports:
      - "26656" # p2p
      - "26657" # http rpc
  interface:
    restart: unless-stopped
    profiles:
      - interface
    build:
      dockerfile: docker/namada-interface.Dockerfile
      context: .
    image: arashidos/namada-interface:${INTERFACE_TAG}
    entrypoint: [ "sh", "/docker-entrypoint-scripts.d/start-node.sh" ]
    hostname: namada-interface
    env_file:
      - .env
    networks:
      namada:
    volumes:
      - ./config/namada-interface-entrypoint.sh:/docker-entrypoint-scripts.d/start-node.sh
      - namada-shared:/root/.namada-shared
      - namada-interface:/root/.local/share/namada
      - ./extensions:/build
    ports:
      - "${INTERFACE_PORT}:3000"
  namada-chain-b:
    <<: *namada-common
    hostname: chain-b
    profiles:
      - hermes
    environment:
      - GENESIS_DELAY=${GENESIS_DELAY}
      - EXTIP=${EXTIP}
    volumes:
      - ./config/genesis-chain-b:/genesis:ro
      - ./config/make_balances.py:/scripts/make_balances.py
      - ./masp-params:/root/.masp-params
      - ./config/start-chain-b.sh:/docker-entrypoint-scripts.d/start-node.sh
      - namada-shared:/root/.namada-shared
      - namada-chain-b_data:/root/.local/share/namada
  hermes:
    image: arashidos/hermes:1.7.4-namada-long-memo
    build:
      dockerfile: docker/bakkhermes.Dockerfile
      context: .
      args:
        - HERMES_TAG=${HERMES_TAG}
    hostname: hermes
    profiles:
      - hermes
    entrypoint: ["sh", "/docker-entrypoint-scripts.d/start.sh"]
    networks:
      namada:
    volumes:
      - ./config/hermes/config-template.toml:/root/config-template.toml
      - ./config/hermes/start.sh:/docker-entrypoint-scripts.d/start.sh
      - namada-shared:/root/.namada-shared
      - hermes:/root/.hermes
volumes:
  namada-1_data:
  namada-2_data:
  namada-3_data:
  namada-chain-b_data:
  namada-shared:
  namada-interface:
  hermes:

networks:
  namada: