[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 10
clear_on_start = false
tx_confirmation = true

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'local.5d5bde592f94bb98c958c8b3'  # set your chain ID #TODO: update this using script
type = 'Namada'
rpc_addr = 'http://namada-1:26657'  # set the IP and the port of the chain
grpc_addr = 'http://namada-1:9090'  # not used for now
event_source = { mode = 'push', url = 'ws://namada-1:26657/websocket', batch_delay = '500ms' }  # set the IP and the port of the chain
account_prefix = ''  # not used
key_name = 'relayer'  # The key is an account name you made
store_prefix = 'ibc'
gas_price = { price = 0.001, denom = 'tnam1q87wtaqqtlwkw927gaff34hgda36huk0kgry692a' }  #TODO: update this using script # the price isn't used for now, the denom should be a raw token address
trusting_period = '1333s'
rpc_timeout = '60s'

[[chains]]
id = 'local.fd43406dd6b18a81562ba9a4'
type = 'Namada'
rpc_addr = 'http://namada-chain-b:26657'
grpc_addr = 'http://namada-chain-b:9090'
event_source = { mode = 'push', url = 'ws://namada-chain-b:26657/websocket', batch_delay = '500ms' }
account_prefix = ''
key_name = 'relayer'
store_prefix = 'ibc'
gas_price = { price = 0.001, denom = 'tnam1q87wtaqqtlwkw927gaff34hgda36huk0kgry692a' } #TODO: update this using script
trusting_period = '1333s' #TODO : use it in mainnet
rpc_timeout = '60s'