#!/usr/bin/env bash
# Set the number of genesis validators in the local Namada network.
#
#   ./scripts/set-validators.sh 6
#
# Writes VALIDATOR_COUNT to .env and generates docker-compose.override.yml so
# that `docker compose --profile main up -d` brings up exactly that many
# validators. docker-compose.yml itself is never modified.
#
# The validator set is baked into genesis, so a change only takes effect on a
# fresh network. Tear the old one down first:
#
#   docker compose --profile main down -v -t 0
set -euo pipefail

# the validators defined directly in docker-compose.yml
BASE_COUNT=3

cd "$(dirname "$0")/.."

OVERRIDE_FILE="docker-compose.override.yml"
ENV_FILE=".env"

usage() {
  echo "Usage: $0 <number-of-validators>" >&2
  echo "  <number-of-validators> must be an integer >= 1" >&2
  exit 1
}

[ $# -eq 1 ] || usage
COUNT=$1
case "$COUNT" in
  ''|*[!0-9]*) usage ;;
esac
[ "$COUNT" -ge 1 ] || usage

# --- update .env -------------------------------------------------------------
# .env is gitignored, so create it from the sample if the user has not yet.
if [ ! -f "$ENV_FILE" ]; then
  echo "No $ENV_FILE found, creating one from .env.sample"
  cp .env.sample "$ENV_FILE"
fi

if grep -q '^VALIDATOR_COUNT=' "$ENV_FILE"; then
  # portable in-place edit: BSD sed (macOS) requires an argument to -i
  sed "s/^VALIDATOR_COUNT=.*/VALIDATOR_COUNT=$COUNT/" "$ENV_FILE" > "$ENV_FILE.tmp"
  mv "$ENV_FILE.tmp" "$ENV_FILE"
else
  printf '\n# number of genesis validators, managed by scripts/set-validators.sh\nVALIDATOR_COUNT=%s\n' "$COUNT" >> "$ENV_FILE"
fi

# --- generate the override ---------------------------------------------------
if [ "$COUNT" -eq "$BASE_COUNT" ]; then
  rm -f "$OVERRIDE_FILE"
  echo "Removed $OVERRIDE_FILE (docker-compose.yml already defines $BASE_COUNT validators)"
  echo
  echo "Validator count set to $COUNT."
  echo "Run 'docker compose --profile main down -v -t 0' before starting, the validator set is fixed at genesis."
  exit 0
fi

{
  echo "# GENERATED by scripts/set-validators.sh -- do not edit by hand."
  echo "# Recreate with: ./scripts/set-validators.sh $COUNT"
  echo "#"
  echo "# Compose loads this file automatically alongside docker-compose.yml,"
  echo "# so no -f flags are needed."
  echo ""
  echo "services:"
} > "$OVERRIDE_FILE"

if [ "$COUNT" -lt "$BASE_COUNT" ]; then
  # Compose overrides cannot delete a service, so move the surplus validators
  # out of the 'main' profile instead. They stay defined but never start.
  # !override is required: without it Compose appends to the profiles list
  # instead of replacing it, so 'main' would survive and the service would
  # still start.
  for i in $(seq $((COUNT + 1)) "$BASE_COUNT"); do
    cat >> "$OVERRIDE_FILE" <<EOF
  namada-$i:
    profiles: !override
      - disabled
EOF
  done
else
  # YAML anchors do not carry across files, so each added validator repeats the
  # service definition. This mirrors the namada-3 block in docker-compose.yml.
  for i in $(seq $((BASE_COUNT + 1)) "$COUNT"); do
    cat >> "$OVERRIDE_FILE" <<EOF
  namada-$i:
    restart: unless-stopped
    build:
      dockerfile: docker/Dockerfile
      context: .
      args:
        - NAMADA_TAG=\${NAMADA_TAG:-v201.0.9}
        - BUILD_WASM=true
    image: ghcr.io/emberstake/namada-selfhost/namada:\${NAMADA_TAG:-v201.0.9}
    entrypoint: ["sh", "/docker-entrypoint-scripts.d/start-node.sh"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      namada:
    hostname: namada-$i
    profiles:
      - main
    volumes:
      - ./masp-params:/root/.masp-params
      - ./config/start-node.sh:/docker-entrypoint-scripts.d/start-node.sh
      - namada-shared:/root/.namada-shared
      - namada-${i}_data:/root/.local/share/namada
    ports:
      - "26656" # p2p
      - "26657" # http rpc
EOF
  done

  echo "" >> "$OVERRIDE_FILE"
  echo "volumes:" >> "$OVERRIDE_FILE"
  for i in $(seq $((BASE_COUNT + 1)) "$COUNT"); do
    echo "  namada-${i}_data:" >> "$OVERRIDE_FILE"
  done
fi

echo "Wrote $OVERRIDE_FILE for $COUNT validators (namada-1 .. namada-$COUNT)"
echo "Set VALIDATOR_COUNT=$COUNT in $ENV_FILE"
echo
echo "Validator count set to $COUNT."
echo "Run 'docker compose --profile main down -v -t 0' before starting, the validator set is fixed at genesis."
