# Genesis token balances to be added here during startup
# note that addresses will be automatically populated during the first run of containers

[token.NAM]

[token.BTC]

[token.ETH]

[token.DOT]

[token.Schnitzel]

[token.Apfel]

[token.Kartoffel]
